spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.badminton.academy: DEBUG
    org.springframework.security: DEBUG

app:
  seed-data: true

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:badminton-academy-images-dev}
    region: ${AWS_S3_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY:your-dev-access-key}
    secret-key: ${AWS_SECRET_KEY:your-dev-secret-key}
